import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import Start from '@/component/Start';

import { BackHand, Diversity2Outlined } from "@mui/icons-material";

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Start />
      </main>
    </div>
  );
}
